# Generated by Django 3.0.2 on 2020-02-05 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0002_auto_20200202_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytic',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('bookid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelf.Book')),
            ],
        ),
    ]
