# Generated by Django 3.0.2 on 2020-02-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0003_analytic'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytic',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analytic',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
