# Generated by Django 3.0.2 on 2020-02-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0004_auto_20200209_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('photoid', models.CharField(max_length=250)),
            ],
        ),
    ]
